#!/usr/bin/env python3
"""Export Instagram session cookies to a Netscape cookie file.

Usage:
    uv run python scripts/export_instagram_cookies.py

Reads INSTAGRAM_USERNAME, INSTAGRAM_PASSWORD, and INSTAGRAM_COOKIES_FILE from .env.
Writes a Netscape-format cookies file that yt-dlp and gallery-dl can consume.
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv
import instaloader


def _to_netscape_line(cookie: object) -> str:
    domain: str = getattr(cookie, "domain", "")
    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
    path: str = getattr(cookie, "path", "/") or "/"
    secure = "TRUE" if getattr(cookie, "secure", False) else "FALSE"
    expires = int(getattr(cookie, "expires", None) or 0)
    name: str = getattr(cookie, "name", "")
    value: str = getattr(cookie, "value", "")
    return f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}"


def main() -> None:
    load_dotenv()

    username = os.environ.get("INSTAGRAM_USERNAME")
    password = os.environ.get("INSTAGRAM_PASSWORD")
    cookies_path = os.environ.get("INSTAGRAM_COOKIES_FILE", "instagram-cookies.txt")

    if not username:
        print("ERROR: INSTAGRAM_USERNAME is not set in .env", file=sys.stderr)
        sys.exit(1)
    if not password:
        print("ERROR: INSTAGRAM_PASSWORD is not set in .env", file=sys.stderr)
        sys.exit(1)

    print(f"Logging in as {username} ...")
    loader = instaloader.Instaloader()
    try:
        loader.login(username, password)
    except instaloader.TwoFactorAuthRequiredException:
        print(
            "ERROR: 2FA is enabled on this account. "
            "Disable 2FA or export cookies manually from a browser.",
            file=sys.stderr,
        )
        sys.exit(1)
    except instaloader.BadCredentialsException:
        print("ERROR: Bad credentials — check INSTAGRAM_USERNAME and INSTAGRAM_PASSWORD.", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: Login failed: {e}", file=sys.stderr)
        sys.exit(1)

    cookies = loader.context._session.cookies
    lines = ["# Netscape HTTP Cookie File", "# Generated by export_instagram_cookies.py", ""]
    for cookie in cookies:
        lines.append(_to_netscape_line(cookie))

    out = Path(cookies_path)
    out.write_text("\n".join(lines) + "\n")
    print(f"Cookies written to: {out.resolve()}")
    print(f"Set in .env:  INSTAGRAM_COOKIES_FILE={out.resolve()}")


if __name__ == "__main__":
    main()
